### ISSUE TITLE
ModuleNotFoundError: No module named 'Eratosthenes

### ISSUE THREAD

**Issue by albertiniufu** [amandaclare/lyndon-factors#1]
When running, I got this error: ModuleNotFoundError: No module named 'Eratosthenes'

I solved this also using https://www.ics.uci.edu/~eppstein/PADS/Eratosthenes.py  besides Eppstein's Lyndon.py

**Comment by amandaclare** [comment]
Thanks, I've now added that to the [README.md](https://github.com/amandaclare/lyndon-factors/blob/master/README.md)
